 name: Update README - gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '0 0 * * *' # taeglich
   workflow_dispatch:
   
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: jasineri/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: Huluvu424242
            # Text on contribution graph 
            text: Welcome
       - uses: jasineri/simple-push-action@v1
